/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import java.util.ArrayList;
import java.util.List;

import entidades.Cliente;
import servicos.Administracao;
import servicos.Estoque;
/**
 *
 * @author vinic
 */
public class fVenda extends javax.swing.JFrame {
    Administracao adm = new Administracao();
    Estoque est = new Estoque();
    List<Cliente> clientes = new ArrayList<>();
    
    /** Creates new form fVenda */
    public fVenda() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoClienteLabel = new javax.swing.JLabel();
        nomeClienteLabel = new javax.swing.JLabel();
        codigoClienteTxt = new javax.swing.JTextField();
        codigoProdutoLabel = new javax.swing.JLabel();
        codigoProdutoText = new javax.swing.JTextField();
        nomeProdutoLabel = new javax.swing.JLabel();
        quantidadeLabel = new javax.swing.JLabel();
        quantidadeProdutoText = new javax.swing.JTextField();
        adicionarProdutosBotao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaVenda = new javax.swing.JTable();
        finalizarVendaBotao = new javax.swing.JButton();
        cancelarVendaBotao = new javax.swing.JButton();
        valorTotalLabel = new javax.swing.JLabel();
        valorTotalText = new javax.swing.JTextField();
        nomeClienteComboBox = new javax.swing.JComboBox<>();
        nomeProdutoComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigoClienteLabel.setText("Código cliente:");

        nomeClienteLabel.setText("Nome cliente:");

        codigoClienteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoClienteTxtActionPerformed(evt);
            }
        });

        codigoProdutoLabel.setText("Código Produto:");

        codigoProdutoText.setText("jTextField3");

        nomeProdutoLabel.setText("Nome produto:");

        quantidadeLabel.setText("Quantidade:");

        quantidadeProdutoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeProdutoTextActionPerformed(evt);
            }
        });

        adicionarProdutosBotao.setText("Adicionar");
        adicionarProdutosBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarProdutosBotaoActionPerformed(evt);
            }
        });

        jTabelaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Prod.", "Nome", "Quant.", "Preço Unit.", "Preço total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabelaVenda);
        if (jTabelaVenda.getColumnModel().getColumnCount() > 0) {
            jTabelaVenda.getColumnModel().getColumn(0).setMinWidth(70);
            jTabelaVenda.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTabelaVenda.getColumnModel().getColumn(0).setMaxWidth(70);
            jTabelaVenda.getColumnModel().getColumn(2).setMinWidth(60);
            jTabelaVenda.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTabelaVenda.getColumnModel().getColumn(2).setMaxWidth(60);
            jTabelaVenda.getColumnModel().getColumn(3).setMinWidth(90);
            jTabelaVenda.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTabelaVenda.getColumnModel().getColumn(3).setMaxWidth(90);
            jTabelaVenda.getColumnModel().getColumn(4).setMinWidth(90);
            jTabelaVenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTabelaVenda.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        finalizarVendaBotao.setText("Finalizar");

        cancelarVendaBotao.setText("Cancelar");

        valorTotalLabel.setText("Valor total:");
        valorTotalLabel.setName(""); // NOI18N

        valorTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTotalTextActionPerformed(evt);
            }
        });

        nomeClienteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nomeClienteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteComboBoxActionPerformed(evt);
            }
        });

        nomeProdutoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(codigoClienteLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(codigoClienteTxt))
                            .add(codigoProdutoLabel)
                            .add(codigoProdutoText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(29, 29, 29)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(nomeProdutoLabel)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(nomeClienteLabel)
                                    .add(nomeProdutoComboBox, 0, 362, Short.MAX_VALUE)
                                    .add(nomeClienteComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(quantidadeLabel)
                            .add(layout.createSequentialGroup()
                                .add(quantidadeProdutoText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(adicionarProdutosBotao))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cancelarVendaBotao)
                        .add(18, 546, Short.MAX_VALUE)
                        .add(finalizarVendaBotao))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(valorTotalLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(valorTotalText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(codigoClienteLabel)
                    .add(nomeClienteLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(codigoClienteTxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nomeClienteComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(codigoProdutoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nomeProdutoLabel)
                    .add(quantidadeLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(codigoProdutoText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(quantidadeProdutoText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(adicionarProdutosBotao)
                    .add(nomeProdutoComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(valorTotalText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(valorTotalLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(finalizarVendaBotao)
                    .add(cancelarVendaBotao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoClienteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoClienteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoClienteTxtActionPerformed

    private void quantidadeProdutoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeProdutoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeProdutoTextActionPerformed

    private void adicionarProdutosBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarProdutosBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarProdutosBotaoActionPerformed

    private void valorTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTotalTextActionPerformed

    private void nomeClienteComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fVenda().setVisible(true);
            }
        });
    }
    
    private void listarClientes(){
        Cliente cliente = new Cliente();
        nomeClienteComboBox.removeAllItems();
        clientes = adm.getClientes();
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarProdutosBotao;
    private javax.swing.JButton cancelarVendaBotao;
    private javax.swing.JLabel codigoClienteLabel;
    private javax.swing.JTextField codigoClienteTxt;
    private javax.swing.JLabel codigoProdutoLabel;
    private javax.swing.JTextField codigoProdutoText;
    private javax.swing.JButton finalizarVendaBotao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaVenda;
    private javax.swing.JComboBox<String> nomeClienteComboBox;
    private javax.swing.JLabel nomeClienteLabel;
    private javax.swing.JComboBox<String> nomeProdutoComboBox;
    private javax.swing.JLabel nomeProdutoLabel;
    private javax.swing.JLabel quantidadeLabel;
    private javax.swing.JTextField quantidadeProdutoText;
    private javax.swing.JLabel valorTotalLabel;
    private javax.swing.JTextField valorTotalText;
    // End of variables declaration//GEN-END:variables

}
