/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidades.Administrador;
import entidades.GestorDeEstoque;
import servicos.Administracao;
import servicos.Estoque;
import banco.Arquivos;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class jMenu extends javax.swing.JFrame {
    Administracao adm;
    Administrador administrador;
    Estoque est;
    GestorDeEstoque gestor;
    Arquivos arq;
    /**
     * Creates new form jMenu
     */
    public jMenu() {
        initComponents();
    }
    /**
     * Creates new form jMenu
     * @param adm
     * @param estoque
     * @param gestor
     * @param administrador
     * @param arq
     */
    public jMenu(Administracao adm,Estoque estoque,GestorDeEstoque gestor,Administrador administrador, Arquivos arq) {
        initComponents();
        this.est = estoque;
        this.adm = adm;
        this.gestor = gestor;
        this.administrador = administrador;   
        this.arq = arq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenu = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jButtonProduto = new javax.swing.JButton();
        jButtonCategorias = new javax.swing.JButton();
        jButtonCaixa = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabelMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenu.setText("Menu");

        jButtonClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonClientes.setText("Clientes");
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonProduto.setText("Produtos");
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });

        jButtonCategorias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCategorias.setText("Categorias");
        jButtonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriasActionPerformed(evt);
            }
        });

        jButtonCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCaixa.setText("Caixa");
        jButtonCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaixaActionPerformed(evt);
            }
        });

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/png-clipart-online-marketplace-marketing-e-commerce-shopping-marketplace-logo-supermarket.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabelMenu))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jButtonCategorias))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonProduto))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jButtonFechar))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jButtonClientes))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelMenu))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jButtonCategorias))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jButtonProduto))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jButtonFechar))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButtonCaixa))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /*
    Chama a tela de opcoes das categorias
    */
    private void jButtonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriasActionPerformed
        // Botão categoria
        JCategoria categoria = new JCategoria(est, gestor);
        categoria.setVisible(true);
    }//GEN-LAST:event_jButtonCategoriasActionPerformed

    /*
    Chama a tela do caixa aja clientes e produtos cadastrados
    */
    private void jButtonCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaixaActionPerformed
        //Botão do caixa
        if(adm.getClientes().isEmpty() || est.getProdutosCadastrados().isEmpty()){
            JOptionPane.showMessageDialog(null, "Não é possível abrir o caixa. Para iniciar uma venda, é necessario ter cadastros de clientes e produtos.");
        }else{
            JCaixa caixa = new JCaixa(adm,est,administrador);
            caixa.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonCaixaActionPerformed

    /*
    Chama a tela de opcoes dos clientes
    */
    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        // Botão cliente
        JClientes clientes = new JClientes(adm,administrador);
        clientes.setVisible(true);
    }//GEN-LAST:event_jButtonClientesActionPerformed

    /*
    Chama a tela de opcoes dos produtos
    */
    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        // Botão produtos
        JProdutos produtos = new JProdutos(est,gestor);
        produtos.setVisible(true);
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // Botão fechar
        arq.carregarArquivos();
        System.exit(0);
    }//GEN-LAST:event_jButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCaixa;
    private javax.swing.JButton jButtonCategorias;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMenu;
    // End of variables declaration//GEN-END:variables
}
